ScrapException: fix (String, Element) constructor
This obvious typo was causing missing information in error reports.

Signed-off-by: Jose Diaz de Grenu <Jose.DiazdeGrenu@digi.com>